[project]
name = "hexlet-code"
version = "0.1.0"
description = "Simple Flask app for the Hexlet DevOps project"
readme = "README.md"
authors = [
    { name = "anatoly", email = "vorobyev.93@mail.ru" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.117.1",
    "gunicorn>=23.0.0",
    "psycopg[binary]>=3.2.10",
    "python-dotenv>=1.1.1",
    "sentry-sdk[fastapi]>=2.39.0",
    "sqlmodel>=0.0.25",
    "uvicorn>=0.36.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
    "ruff>=0.13.0",
]

[project.scripts]
hexlet-code = "main:run"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
